### ISSUE TITLE
Local user data location

### ISSUE THREAD

**Issue by ivan-cukic** [hughsie/appdata-tools#11]
This is slightly more technical than the metadata covered by the current spec, but could be very useful.

Every application knows where it stores its user configuration (.vimrc, .config/libreoffice/4, etc.) and the data (.vim, .local/share/akonadi).

Potential usage:
- Package manager: optionally deleting user data after uninstallation
- Personal data backup
- Data synchronization between devices
- Automatic application sandboxing (to be able to access only things defined in the spec)

**Comment by hughsie** [comment]
Although I do think this is a good idea to store somewhere, I'm not sure it fits in the AppData file as it's not really anything to do with the software center. Also, distro don't have to set any specific directories (thanks to xdg-user-dir) so I'm not sure how we'd encode such a thing anyway.
