### ISSUE TITLE
make name and summary mandatory

### ISSUE THREAD

**Issue by mlschroe** [hughsie/appdata-tools#21]
the standard currently says that it's ok to leave out the name/summary from the appdata.xml file. In that case, the parser will take the entries from the corresponding .desktop file.
This slows down parsing quite a bit, as for every appdata file a second file has to be opened and parsed. Please consider making them mandatory.

The use case is package managers like 'zypper' having an option to display all installed applications.

**Comment by hughsie** [comment]
We're now making missing name and summary tags a validation failure.
