### ISSUE TITLE
Support Qt localization files

### ISSUE THREAD

**Issue by GreenLunar** [hughsie/appdata-tools#26]
Support parsing of `.qm` files for language availability/statistics.

@qtproject
@ossilator

**Comment by hughsie** [comment]
Okay, I've got some time to look at this now. Some questions:

* What applications use the QM format? I see most open source apps seem to use gettext
* What's the binary format of a .qm file? I can see what looks like UTF-16 encoded translations, but I can't add a dep on Qt in the builder for obvious reasons

Thanks!

**Comment by ossilator** [comment]
no applications except those using qt use .qm files. at least there aren't many reasons to do so.

the only documentation of the format is the implementation:
http://code.qt.io/cgit/qt/qttools.git/tree/src/linguist/shared/qm.cpp
http://code.qt.io/cgit/qt/qtbase.git/tree/src/corelib/kernel/qtranslator.cpp

**Comment by hughsie** [comment]
Thanks for those links, that looks an easy enough format to parse. Other than the QT apps (like qt-creator) are there any free games or apps I can download to test my code?

**Comment by ossilator** [comment]
i haven't been tracking what's happening outside qt itself. but i think the qt-creator and qttranslations repos provide enough material for playing. :)
fwiw, there are also proper autotests which you may want to simply lift the data files from: http://code.qt.io/cgit/qt/qttools.git/tree/tests/auto/linguist/lrelease

**Comment by GreenLunar** [comment]
> are there any free games or apps I can download to test my code?

Th first is a top-down racing game, the rest are board games.

```
Skill
http://dustrac.sourceforge.net/ (requires OpenGL)
http://qt-apps.org/content/show.php?content=140171

Mind
http://colorcode.laebisch.com/
https://github.com/w0301/TicTacToe
http://gottcode.org/cutemaze/
http://gottcode.org/peg-e/
http://gottcode.org/simsu/
http://gottcode.org/tetzle/
http://kapitalist.sourceforge.net/ (Qt3)
http://qt-apps.org/content/show.php?content=113173
http://qt-apps.org/content/show.php?content=122899
http://sourceforge.net/projects/capitalism/
http://sourceforge.net/projects/pacmanlike/
http://sourceforge.net/projects/tictactoe-qt/
http://sourceforge.net/projects/tttfh/
http://tubularix.sourceforge.net/
```
