### ISSUE TITLE
Using CC0 means we have to include that license text in our tarballs

### ISSUE THREAD

**Issue by cbm755** [hughsie/appdata-tools#27]
(apologies if this is not the correct place to report/discuss this).

@oheim noted that he "[prefers not to] use CC0, because then
I'd have to bundle that license text in the release."  This is assuming (as is probably common) that nothing else in a project is CC0 licensed.  I think this is a valid concern.

We think that an appropriate license for these sorts of small files is:
http://www.gnu.org/licenses/license-list.en.html#GNUAllPermissive

Benefits:
  * text itself goes inside the file (only 4 lines)
  * appdata can relicense to CC0 if needed when making the big blob (please excuse my technical ignorance about what you actual do with the `metainfo.xml` file, but I certainly understand you wish to repackage it).

Downsides
  * no SPDX thingy?
  * no longer strict subset of appstream?

Thoughts?

**Comment by hughsie** [comment]
I'd be happy adding GNUAllPermissive to the valid metadata licences if it has a SPDX ID. If it helps, 99% of the AppData and MetaInfo files are CC0, and the other 1% are a mix of CC-BY-SA and GFDL.

**Comment by cbm755** [comment]
but how do other projects avoid shipping CC0 license text?  And then fedora spec files become `License:        GPLv3+ and CC0`, etc, etc...

**Comment by oheim** [comment]
I didn't check the histories, but SPDX ID `FSFULLR` could be an old version of GNUAllPermissive.

**Comment by cbm755** [comment]
hmmm, that sounds rather specific usage and has FSF hardcoded...

**Comment by cbm755** [comment]
(I mean if you put your own name in, is it still FSFULLR?)

**Comment by hughsie** [comment]
Most Fedora packages just ignore the trivial CC0 addition. Some add it but I think it's completely useless information as there's nothing you can't do with CC0. `FSFUL` looks like a valid metadata licence, although it does seem configure-specific. GFDL seems like a good FSF license for this kind of documentation file if you don't want a CC-style license, although Debian seems to not like GFDL for some reason.

**Comment by cbm755** [comment]
Thanks!  GFDL just feels a bit "heavy" for this task.  I don't have a problem with CC0.  I just think its common practice to ship the license text of all licenses used in one's software.

**Comment by cbm755** [comment]
I looked into requested GNU-All-Permissive for SPDX... And good news, looks Didier Verna proposed it already and its been accepted [1].  I think its SPDX-ID will be `All-Permissive`.

[1] http://wiki.spdx.org/view/Legal_Team/License_List/Licenses_Under_Consideration, have to follow the first link to an online spreadsheet.

**Comment by oheim** [comment]
> hmmm, that sounds rather specific usage and has FSF hardcoded...

The license has been published in a manual for GNU software, where copyright assignment to the FSF has been common practice. The current version of the license clearly separates the copyright statement from the license.

> Most Fedora packages just ignore the trivial CC0 addition. Some add it but I think it's completely useless information as there's nothing you can't do with CC0.

The exact license text must be delivered to the licensee. As soon as the package is part of a distribution, where common licenses can be found in /usr/share/… you don't have to duplicate it over and over again. But as a distributor of a single upstream package I have to bundle the license text. And since CC0 is used nowhere else in my software package, I would paste the license text (as an xml comment) into the metainfo file. This would be much simpler with `All-Permissive`.

> Debian seems to not like GFDL for some reason

Debian considers the license as “non-free” if you use the feature “with invariant sections.” Without this (optional) feature (that almost nobody uses), Debian is fine with GFDL.

> I think its SPDX-ID will be All-Permissive.

Yes, looks like it is going to be in the 2.3 release.

**Comment by cbm755** [comment]
@hughsie, is that ok?  Totally understand if you prefer to wait until the next SPDX release.

@oheim I propose we (a) include the license text inside the copyright header (as you already did) and (b) set the metadata_license tag to `All-Permissive`?  I will then update my patches for other octave-forge packages (want to add keywords too).

**Comment by cbm755** [comment]
> Yes, looks like it is going to be in the 2.3 release.

Well 2.3 is out... they might mean "approved while 2.3 was current release."  OTOH, some are listed as "accepted in v2.4"...

Anyway, I'd bet its in the next release.

**Comment by oheim** [comment]
@cbm755, sounds good. But I wonder whether we have to wait for the next SPDX release or for a new appdata release in order to not cause havoc in the appdata distributions. ;-) So let's wait for @hughsie's answer.

**Comment by cbm755** [comment]
> Yes, looks like it is going to be in the 2.3 release.

Maybe it was an error.  Because the other things listed as "accepted in v2.3" really are in v2.3.  I will if I can contact them...

**Comment by cbm755** [comment]
I wrote an email to them, will report back when I hear something: I suspect its been overlooked b/c it comes after a bunch of "rejected" licenses in the online spreadsheet.  And its not mentioned in the git repo at all.

**Comment by hughsie** [comment]
Yes, I do need to wait for All-Permissive to be included in a SPDX release before I can add it in appstream-glib as a valid metadata tag. @cbm755 when you hear please let me know also. It might just be easier to use CC0 and just include the CC0 license text next to the AppData file. FWIW, I don't know of any other upstream software shipping an AppData file under CC0 that includes the CC full license as a file, but I do understand if this is what you want to do.

**Comment by cbm755** [comment]
I've now heard back from the spdx folks [1].  They will use the short code "FSFAP" and it will be in their next release [1] which will be 2.4.  Note it *will not* be called "All Permissive".  I will need to update my patches.

[1] http://lists.spdx.org/pipermail/spdx-legal/2016-February/001641.html

@hughsie is that official enough to patch your software?  I'm not sure when 2.4 will be out, but I guess it could be a couple months based on past frequency.

**Comment by hughsie** [comment]
Yup, I'm happy to add FSFAP at this stage.

**Comment by cbm755** [comment]
Thank you!
